# Generated by Django 5.2.3 on 2025-06-30 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_sentimentmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentimentMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
